In [2]:
import geopandas

import geopandas as gpd
import pandas as pd

In [3]:
import pandas as pd
import dask.dataframe as dd

In [4]:
import numpy as np

In [ ]:
filename='/Users/jiaqitang/Downloads/gdp_ppp_30_2000.csv'

In [ ]:
with open(filename, "r") as f:
    lines = csv.reader(f)
    for line in lines:

In [ ]:
df_train = dd.read_csv('../data/train.csv', usecols=[col1, col2])
df_train=df_train.compute()
print("load train: " , time.clock()-t)

In [32]:
col_Names=["lat", "long", "gdpp"]

gdpcsv=pd.read_csv('/Users/jiaqitang/Downloads/gdp_ppp.csv',names=col_Names)

In [33]:
gdpcsv.head()

         lat       long gdpp
0  89.958336 -179.95833   --
1  89.958336 -179.87500   --
2  89.958336 -179.79166   --
3  89.958336 -179.70833   --
4  89.958336 -179.62500   --

In [34]:
gdpcsv=gdpcsv.loc[gdpcsv['gdpp'] !='--']
#gdpcsv['gdpp'] = gdpcsv['gdpp'].astype(float)
#gdpcsv=gdpcsv.loc[gdpcsv['gdpp']>0]
gdpcsv=gdpcsv[gdpcsv['long']!= 'long']
gdpcsv['long']  =gdpcsv['long'] .astype(float)
gdpcsv['lat']  =gdpcsv['lat'] .astype(float)
gdpcsv['gdpp'] = gdpcsv['gdpp'].astype(float)
gdpcsv=gdpcsv.loc[gdpcsv['gdpp']>0]
gdpcsv['long']=gdpcsv['long']*(-10000)
gdpcsv['lat']=gdpcsv['lat']*(-10000000)

In [35]:
gdpcsv.to_csv('/Users/jiaqitang/Downloads/gdp_ppp_5_new5_e.csv')

In [26]:
gdpcsvt=pd.read_csv('/Users/jiaqitang/Downloads/gdp_ppp_5_new5_e.csv')

In [27]:
gdpcsvt.head()

   Unnamed: 0          lat       long       gdpp
0      559628  792083360.0  157083.28    83117.3
1      563954  791250000.0  162083.28    83117.3
2      585559  787083360.0  166250.00    83117.3
3      589875  786250000.0  162916.72  1163642.2
4      589876  786250000.0  163750.00  3989630.2

In [6]:
col_Names=["lat", "long", "gdpp"]

In [12]:
gdpcsv1=pd.read_csv('/Users/jiaqitang/Downloads/gdp_ppp_30.csv',names=col_Names,chunksize=100000)

In [7]:

gdpcsv1=pd.read_csv('/Users/jiaqitang/Downloads/gdp_ppp_30.csv',names=col_Names,chunksize=100000)

In [ ]:
gdpcsv=gdpcsv.loc[gdpcsv['gdpp'] !='--']
#gdpcsv['gdpp'] = gdpcsv['gdpp'].astype(float)
#gdpcsv=gdpcsv.loc[gdpcsv['gdpp']>0]
gdpcsv=gdpcsv[gdpcsv['long']!= 'long']
gdpcsv['long']  =gdpcsv['long'] .astype(float)
gdpcsv['lat']  =gdpcsv['lat'] .astype(float)
gdpcsv['gdpp'] = gdpcsv['gdpp'].astype(float)
gdpcsv=gdpcsv.loc[gdpcsv['gdpp']>0]
gdpcsv['long']=gdpcsv['long']*10000
gdpcsv['lat']=gdpcsv['lat']*100000+10000000

In [8]:
count=0
for chunk in gdpcsv1:
    
    chunk = chunk[chunk.gdpp!='--']
    
    chunk['gdpp']  = chunk['gdpp'] .astype(float)
    
    chunk=chunk.loc[chunk['gdpp'] !='--']
#gdpcsv['gdpp'] = gdpcsv['gdpp'].astype(float)
#gdpcsv=gdpcsv.loc[gdpcsv['gdpp']>0]
    chunk=chunk[chunk['long']!= 'long']
    chunk['long']  =chunk['long'] .astype(float)
    chunk['lat']  =chunk['lat'] .astype(float)
    chunk['gdpp'] = chunk['gdpp'].astype(float)
    chunk=chunk.loc[chunk['gdpp']>0]
    chunk['long']=chunk['long']*10000
    chunk['lat']=chunk['lat']*100000+10000000
    #print(chunk)
    #chunk= chunk[(chunk['gdpp'] >0)]
    
    chunk.to_csv('/Users/jiaqitang/Downloads/gdp_ppp_30eu.csv',mode='a')

/Users/jiaqitang/anaconda3/lib/python3.7/site-packages/pandas/core/ops.py:1649: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)

In [6]:

gdpcsv=pd.read_csv('/Users/jiaqitang/Downloads/gdp_ppp_30_2000.csv',names=col_Names,chunksize=100000)

In [7]:
count=0
for chunk in gdpcsv:
    
    chunk = chunk[chunk.gdpp!='--']
    
    chunk['gdpp']  = chunk['gdpp'] .astype(float)
    #print(chunk)
    #chunk= chunk[(chunk['gdpp'] >0)]
    
    chunk.to_csv('/Users/jiaqitang/Downloads/gdp_ppp_30_2000_new5.csv',mode='a')

In [72]:
def raises(exception_types, func, *args, **kw):
    try:
        func(*args, **kw)
    except exception_types:
        return True
    else:
        return False

In [75]:

col_Names=["check","lat", "long", "gdpp"]
gdpcsv2=pd.read_csv('/Users/jiaqitang/Downloads/gdp_ppp_30new5.csv')

In [85]:
gdpcsv2['long'][1].isdigit()

False

In [93]:
gdpcsv2=gdpcsv2[gdpcsv2['long']!= 'long']

In [86]:
gdpcsv3 = gdpcsv2.apply(pd.to_numeric, errors='ignore')

In [91]:
float(gdpcsv3['long'][1])

-23.954163

In [73]:
mynewlist = [item for item in gdpcsv2['long'] if not raises(ValueError, float, item)]

In [80]:
gdpcsv2['long'][0].isnumeric()

False

In [ ]:
gdpcsv2[s for s in gdpcsv2['long'] if s.isdigit()]

In [60]:
gdpcsv2[gdpcsv2['long'].str.isdigit()]

Empty DataFrame
Columns: [Unnamed: 0, lat, long, gdpp]
Index: []

In [54]:
gdpcsv2=gdpcsv2[gdpcsv2['lat'].str.isdigit()==True]

In [95]:
gdpcsv2['long']  =gdpcsv2['long'] .astype(float)
gdpcsv2['lat']  =gdpcsv2['lat'] .astype(float)
gdpcsv2['gdpp'] = gdpcsv2['gdpp'].astype(float)

In [96]:
gdpcsv2

           Unnamed: 0        lat       long       gdpp
0         130309924.0  64.862500 -23.962494   4490.973
1         130309925.0  64.862500 -23.954163   4490.973
2         130309930.0  64.862500 -23.912506  27852.621
3         130309931.0  64.862500 -23.904160  27852.621
4         130309990.0  64.862500 -23.412506  14562.792
5         130309991.0  64.862500 -23.404160  14562.792
6         130309992.0  64.862500 -23.395828   14192.25
7         130309993.0  64.862500 -23.387497   14192.25
8         130309994.0  64.862500 -23.379166  53141.887
9         130309995.0  64.862500 -23.370834  53141.887
10        130310006.0  64.862500 -23.279160  19629.406
11        130310007.0  64.862500 -23.270828  19629.406
12        130310011.0  64.862500 -23.237488  21398.027
13        130310012.0  64.862500 -23.229156  21398.027
14        130310013.0  64.862500 -23.220825  15185.751
15        130310014.0  64.862500 -23.212494  15185.751
16        130310015.0  64.862500 -23.204178  382286.75
17        130310016.0  64.862500 -23.195847  382286.75
18        130310017.0  64.862500 -23.187500   75117.55
19        130310018.0  64.862500 -23.179169   75117.55
20        130310021.0  64.862500 -23.154175  30047.191
21        130310022.0  64.862500 -23.145844  30047.191
22        130310031.0  64.862500 -23.070831  18640.482
23        130310032.0  64.862500 -23.062500  18640.482
24        130310033.0  64.862500 -23.054169   40401.78
25        130310034.0  64.862500 -23.045837   40401.78
26        130310035.0  64.862500 -23.037506   50991.46
27        130310036.0  64.862500 -23.029175   50991.46
28        130310037.0  64.862500 -23.020828  1128312.4
29        130310038.0  64.862500 -23.012497  1128312.4
...               ...        ...        ...        ...
36415946  756704731.0 -55.970825 -67.237495  354.71152
36415947  756704732.0 -55.970825 -67.229164  118.23716
36415948  756704733.0 -55.970825 -67.220825  118.23716
36415949  756704734.0 -55.970825 -67.212510   709.4229
36415950  756704735.0 -55.970825 -67.204170  118.23716
36415951  756704736.0 -55.970825 -67.195840  118.23716
36415952  756747921.0 -55.979170 -67.320830  118.21185
36415953  756747922.0 -55.979170 -67.312500   827.4829
36415954  756747923.0 -55.979170 -67.304160   827.4829
36415955  756747924.0 -55.979170 -67.295830   1536.754
36415956  756747925.0 -55.979170 -67.287500   1536.754
36415957  756747926.0 -55.979170 -67.279160  1891.3895
36415958  756747927.0 -55.979170 -67.270830  1891.3895
36415959  756747928.0 -55.979170 -67.262500  1891.3895
36415960  756747929.0 -55.979170 -67.254166  354.63556
36415961  756747930.0 -55.979170 -67.245830  354.63556
36415962  756747931.0 -55.979170 -67.237495  118.21185
36415963  756747932.0 -55.979170 -67.229164  118.21185
36415964  756747933.0 -55.979170 -67.220825  709.27106
36415965  756747934.0 -55.979170 -67.212510  118.21185
36415966  756747935.0 -55.979170 -67.204170  118.21185
36415967  756791123.0 -55.987503 -67.304160   590.9327
36415968  756791124.0 -55.987503 -67.295830   590.9327
36415969  756791125.0 -55.987503 -67.287500  1181.8652
36415970  756791126.0 -55.987503 -67.279160  1890.9845
36415971  756791127.0 -55.987503 -67.270830  1890.9845
36415972  756791128.0 -55.987503 -67.262500  1181.8652
36415973  756791129.0 -55.987503 -67.254166  1181.8652
36415974  756791130.0 -55.987503 -67.245830  354.55963
36415975  756791131.0 -55.987503 -67.237495  354.55963

[36409712 rows x 4 columns]

In [ ]:
gdf = geopandas.GeoDataFrame(
    gdpcsv2, geometry=geopandas.points_from_xy(gdpcsv2.long, gdpcsv2.lat))

Exception ignored in: <function BaseGeometry.__del__ at 0x118f451e0>
Traceback (most recent call last):
  File "/Users/jiaqitang/anaconda3/lib/python3.7/site-packages/shapely/geometry/base.py", line 234, in __del__
    self.empty(val=None)
  File "/Users/jiaqitang/anaconda3/lib/python3.7/site-packages/shapely/geometry/base.py", line 227, in empty
    self._lgeos.GEOSGeom_destroy(self.__geom__)
KeyboardInterrupt:
Exception ignored in: <function BaseGeometry.__del__ at 0x118f451e0>
Traceback (most recent call last):
  File "/Users/jiaqitang/anaconda3/lib/python3.7/site-packages/shapely/geometry/base.py", line 234, in __del__
    self.empty(val=None)
  File "/Users/jiaqitang/anaconda3/lib/python3.7/site-packages/shapely/geometry/base.py", line 227, in empty
    self._lgeos.GEOSGeom_destroy(self.__geom__)
KeyboardInterrupt:

In [ ]:
gdpcsv=gdpcsv.loc[gdpcsv['gdpp'] !='--']
gdpcsv['gdpp'] = gdpcsv['gdpp'].astype(float)
gdpcsv=gdpcsv.loc[gdpcsv['gdpp']>0]

In [ ]:
import geopandas
from geopandas.tools import sjoin
import rtree
import geopandas as gpd
import pandas as pd

col_Names=["lat", "long", "gdpp"]

gdpcsv=pd.read_csv('/Users/jiaqitang/Downloads/gdp_ppp_30.csv',names=col_Names)
gdpcsv=gdpcsv.loc[gdpcsv['gdpp'] !='--']
gdpcsv['gdpp'] = gdpcsv['gdpp'].astype(float)
gdpcsv=gdpcsv.loc[gdpcsv['gdpp']>0]

#gdf = geopandas.GeoDataFrame(
#    gdpcsv, geometry=geopandas.points_from_xy(gdpcsv.long, gdpcsv.lat))

In [ ]:
gdpcsv.to_csv("/Users/jiaqitang/Downloads/gdp_ppp_30new.csv")

In [ ]:



gdpcsv=gdpcsv.loc[gdpcsv['gdpp'] !='--']
gdpcsv['gdpp'] = gdpcsv['gdpp'].astype(float)

top = 49.3457868 # north lat
left = -124.7844079 # west long
right = -66.9513812 # east long
bottom =  24.7433195
#pop['geometrypoly']=pop['geometry']
gdpcsv=gdpcsv.loc[gdpcsv['gdpp']>0]
gdpcsvus=gdpcsv.loc[(gdpcsv['lat']>=bottom)&(gdpcsv['lat']<=top)&(gdpcsv['long']>=left)&(gdpcsv['long']<=right)]

In [ ]:
##United States

#Argentina
#Bolivia
#Brazil
#Bulgaria
#Chile
#Croatia
#Czech Republic
#Dominican Republic
#Ecuador
#Estonia
#Finland
#Iceland
#India
#Indonesia
#Israel
#Italy
#Latvia
#Macedonia
#Moldova
#Montenegro
#Peru
#Poland
#Romania
#Russia
#Serbia
#Slovakia
#South Africa
#Spain
#Switzerland